### ISSUE TITLE
Unicode error in project list

### ISSUE THREAD

**Issue by ways** [robinhouston/freckle-command#2]
Hi

Love the script, but got this:

> ± ./freck -l > projects
> Traceback (most recent call last):
>   File "./freck", line 279, in <module>
>     Freckle().list_projects()
>   File "./freck", line 189, in list_projects
>     print "  " + project
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 19: ordinal not in range(128)

**Comment by robinhouston** [comment]
Interesting, thanks! I don’t think I’ve ever had a project with a non-ascii character in its name.

I’ve just pushed a possible fix to the branch [unicode-error](https://github.com/robinhouston/freckle-command/tree/unicode-error). Does that help?

**Comment by ways** [comment]
> Interesting, thanks! I don’t think I’ve ever had a project with a non-ascii character in its name.

Yes, it's not easy to live in a country with lots of weird characters (æøå).

> I’ve just pushed a possible fix to the branch unicode-error. Does that help?

Yes, that seems to have fixed the problem. Will reopen if I hit any other problems.
